org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=false
org.gradle.unsafe.io=true
# 增加更长的超时时间
systemProp.org.gradle.internal.http.connectionTimeout=300000
systemProp.org.gradle.internal.http.socketTimeout=300000
systemProp.http.keepAlive=false
# 启用更多的调试信息
org.gradle.logging.level=info
# 设置较低的内存消耗
org.gradle.workers.max=2
# 不再需要忽略Kotlin JVM目标验证

# 允许不安全的动态代码加载，解决isar_flutter_libs资源问题
android.enableUnsafeDynamicCodeLoading=true
# 解决lStar资源问题
android.suppressUnsupportedCompileSdk=35
# 忽略资源冲突
android.enableResourceOptimizations=false
android.nonTransitiveRClass=false
android.nonFinalResIds=false
